# Generated by Django 5.2 on 2025-04-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Código')),
                ('companions', models.PositiveIntegerField(default=0, verbose_name='Acompanhantes')),
                ('checked_in', models.BooleanField(default=False, verbose_name='Entrou')),
                ('companions_checked_in', models.PositiveIntegerField(default=0, verbose_name='Acomp. presentes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
